import React from 'react';
import sampleImage from '../../assets/careerworkshop/mern and Python.png';

export const BlogData = [

    {
        capTitle:'named model',
        title: "Llama 3.2",
        name: "Llama-3B",
        image:sampleImage,
        updated: 15,
        description: "Llama 3B model uploaded via MLflow for deployment",
        rating: 5,
        reviews: 1,
        uses: 94,
        views: 69,
        price: "0.01",
    },
    {
        capTitle:'seconde named model',
        title: "LLAMA-Health",
        name: "LLAMA-Health",
        updated: 16,
        image: sampleImage,
        description: "AI powered LLaMA model for disease diagnosis and insights",
        rating: 5,
        reviews: 1,
        uses: 24,
        views: 16,
        price: "0.01",
    },
    {
        capTitle: 'named model',
        title: "Llama 3.2",
        name: "Llama-3B",
        updated: 15,
        image: sampleImage,
        description: "Llama 3B model uploaded via MLflow for deployment",
        rating: 5,
        reviews: 1,
        uses: 94,
        views: 69,
        price: "0.01",
    },
    {
        capTitle: 'seconde named model',
        title: "LLAMA-Health",
        name: "LLAMA-Health",
        updated: 16,
        image: sampleImage,
        description: "AI powered LLaMA model for disease diagnosis and insights",
        rating: 5,
        reviews: 1,
        uses: 24,
        views: 16,
        price: "0.01",
    },
];
